### Report temp (cold outside, comfortable inside)
POST http://localhost:8081/thermostat/home-123/temperature
Content-Type: application/json

{
  "indoor_temp": 21.0,
  "outdoor_temp": -15.0
}

### Check status
GET http://localhost:8081/thermostat/home-123/status

### Report temp drop (needs heating)
POST http://localhost:8081/thermostat/home-123/temperature
Content-Type: application/json

{
  "indoor_temp": 18.5,
  "outdoor_temp": -28.0
}

### Raise target
POST http://localhost:8081/thermostat/home-123/target
Content-Type: application/json

{
  "target_temp": 22.0
}