apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: openai
spec:
  type: conversation.openai
  metadata:
    - name: key
      value:
    - name: model
      value: gpt-4o-mini
    - name: endpoint
      value: ""
    - name: cacheTTL
      value: 10m
    - name: apiType # Optional
      value: "azure"
    - name: apiVersion # Optional
      value: "2025-01-01-preview"
