apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: postgrepstatestore
spec:
  type: state.postgresql
  # Note: setting "version" to "v2" is required to use the v2 of the component
  version: v2
  metadata:
    # Connection string
    # - name: connectionString
    #   value: "<CONNECTION STRING>"
    # Individual connection parameters - can be used instead to override connectionString parameters
    - name: host
      value: "localhost"
    #- name: hostaddr
    #  value: "127.0.0.1"
    - name: port
      value: "5432"
    - name: database
      value: "postgres"
    - name: user
      value: "postgres"
    - name: password
      value: "mysecretpassword"
    #- name: sslRootCert
    #  value: "/path/to/ca.crt"
    # Timeout for database operations, as a Go duration or number of seconds (optional)
    #- name: timeout
    #  value: 20
    # Prefix for the table where the data is stored (optional)
    #- name: tablePrefix
    #  value: ""
    # Name of the table where to store metadata used by Dapr (optional)
    #- name: metadataTableName
    #  value: "dapr_metadata"
    # Cleanup interval in seconds, to remove expired rows (optional)
    #- name: cleanupInterval
    #  value: "1h"
    # Maximum number of connections pooled by this component (optional)
    #- name: maxConns
    #  value: 0
    # Max idle time for connections before they're closed (optional)
    #- name: connectionMaxIdleTime
    #  value: 0
    # Controls the default mode for executing queries. (optional)
    #- name: queryExecMode
    #  value: ""
    # Uncomment this if you wish to use PostgreSQL as a state store for actors or workflows (optional)
    #- name: actorStateStore
    #  value: "true"
